#!/bin/sh

# Identificamos al usuario
CURRENT_USER=$USER

# Obtenemos el idioma preferido del usuario
PRE_LANG=$(sudo -u "$CURRENT_USER" defaults read .GlobalPreferences AppleLanguages | tr -d "[:blank:]()\"," | tr "-" "_" | sed '/^$/d' | head -n 1)

# Si no lo hemos encontrado, usaremos el idioma actual
if [ -z "$PRE_LANG" ]; then
	PRE_LANG=$LANG
fi

# Si no hemos encontrado definido el idioma, es probable que esta
case "$PRE_LANG" in
"")
	AFIRMA_LOCALE="en_US"
	;;
en*)
	AFIRMA_LOCALE="en_US"
	;;
ca*)
	AFIRMA_LOCALE="ca_ES"
	;;
eu*)
	AFIRMA_LOCALE="eu_ES"
	;;
gl*)
	AFIRMA_LOCALE="gl_ES"
	;;
va*)
	AFIRMA_LOCALE="va_ES"
	;;
*)
	AFIRMA_LOCALE="es_ES"
	;;
esac

# se ejecuta el configurador
sudo /Applications/Autofirma.app/Contents/Resources/Home/bin/java -jar /Applications/Autofirma.app/Contents/Resources/JAR/autofirmaConfigurador.jar -install -default_language "$AFIRMA_LOCALE"
exit 0
